name : KentSrc

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install firt Alien::libuuid
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::libuuid
      - name: Install Dependencies
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::KentSrc
