name : KentSrcTestNewLibDeps

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install KentSrc
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::KentSrc dirt/Alien-KentSrc-0.5.tar.gz
