name : LibBigWigAlienCurl

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Check file is here
        run: ls dirt
      - name: Install LibBigWig
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure dirt/Alien-LibBigWig-v0.4.3.tar.gz --verbose
