name : LibUSBx-cpanm

on:
  push:
  schedule:
    - cron: 0 12 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install non alienazed dependencies
        run: sudo apt-get install libudev-dev
      - name: Install alien
        run: curl -L https://cpanmin.us | perl - Alien::LibUSBx
