name: libxml2-windows-share

on:
  pull_request:
  schedule:
    - cron: 0 0 * * *

env:
  PERL5LIB: c:\cx\lib\perl5
  PERL_LOCAL_LIB_ROOT: c:/cx
  PERL_MB_OPT: --install_base C:/cx
  PERL_MM_OPT: INSTALL_BASE=C:/cx
  ALIEN_INSTALL_TYPE: share

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "##[add-path]C:\cx\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: perl -V
        run: |
          perl -V
      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          dir perlversion.txt
      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: c:\cx
          key: ${{ runner.os }}-build-share-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-share-${{ hashFiles('perlversion.txt') }}
      - name: Install Dynamic Dependencies
        run: 
          curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::Libxml2
