name: pkgconf-perl-versions-matrix

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.8'
          - '5.10'
          - '5.16'
          - 'latest'
          - 'threaded'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::pkgconf
