name: pkgconf-linux-distributions-matrix
on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        img:
          - 'ubuntu:14.04'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'fedora:26'
          - 'fedora:30'
          #- 'base/archlinux'

          #- 'debian:jessie'
          #- 'debian:bullseye'
          #- 'centos:centos6'
          #- 'centos:centos7'
          #- 'slackware/base'
          #- 'opensuse/leap'
          #- 'opensuse/tumbleweed'
          

    container:
      image: ${{ matrix.img }}

    steps:
      - name: Eventually install Perl on Fedora and centos
        run: yum install perl perl-Digest-MD5 perl-Time-HiRes perl-Data-Dumper -y || true
      - name: perl -V
        run: perl -V
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Alien::pkgconf
